### ISSUE TITLE
A few hacky approaches

### ISSUE THREAD

**Issue by sleepylee** [hoang06kx1/koin-example-android#14]
Not saying that these don't have their pros, but the cons are also needed to consider as well:
 - This [part](https://github.com/hoang06kx1/nbl-survey/blob/ff056b47be8db243fb84c2f25eba3ba3d088fa2a/app/src/main/java/com/hoang/survey/listsurveys/MainActivity.kt#L28) is kinda weird, I'm not very convinced of this, as, for us, it seems like we don't have to do so with our Espresso setup.
 - The [SurverRepositoryHolder](https://github.com/hoang06kx1/nbl-survey/blob/ff056b47be8db243fb84c2f25eba3ba3d088fa2a/app/src/main/java/com/hoang/survey/authentication/AccessTokenAuthenticator.kt#L58) seems to strive for a safe-thread singleton implementation? (correct me if I'm wrong) but I believe we have a better approach with kotlin `object`. Also, I think `SurverRepositoryHolder` does not belong to `AccessTokenAuthenticator`, it is likely that there will be more Repositories that require token auth, so, it's more than just the naming/location problem, it's about the extendability as well 🙏
- This [Error Handler](https://github.com/hoang06kx1/nbl-survey/blob/ff056b47be8db243fb84c2f25eba3ba3d088fa2a/app/src/main/java/com/hoang/survey/SurveyApplication.kt#L22) is something that we are fully in doubt with. Indeed it's good to think for the production stability, but without knowing what exactly going on via a Crash sometimes might be worse. It is also an independent factor to different developer's mindset as well, so we're not bashing you here, but technically, we would not allow our team to put a divine `try catch` to all 🙏 in case of picking this mechanism, I'd prefer to follow the [official documentation](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling) to explicitly define on which occasion should we catch and handle (especially with the UndeliverableException)

**Comment by hoang06kx1** [comment]
- I see this assignment as a chance to practice the latest technologies. So I used the AndrdoidX Test to write Espresso and it seems unstable. I could not get the activity as described [here](https://developer.android.com/guide/components/activities/testing) and forced to use that hacky way as a workaround. I myself don't interesting in that approaching, too. Think twice, I should fall back to AcitivtyTestRuler or stop using the dialog lib which is the main cause of this problem. 

- Yes `SurverRepositoryHolder` should be `Object`. `Object` in Kotlin does not support constructor with params so I use that singleton pattern quite often that I almost forgot about `Object` for no params constructor singleton :pray: You're right about the extendability, I indeed did not think about reusing it.

- It's a half-baked solution from me for handling `RxJava` exceptions. Instead of logging out the throwable (meaningless in production), I will send the `Throwable` back to `Error report system` like Crashlyptics. I have no intention in abusing try/catch to hide the malfunction features. That's why I only enable it in `release` build, to avoid crashes which affect the user's experiences. :smile:

**Comment by sleepylee** [comment]
Overall we can feel that you're a very passionate developer, open for challenges and not hesitate to try out the new things, @hoang06kx1 . It' a great spirit there indeed. It is unfortunate to hear the final decision though, but please don't let it pull you down, keep improving yourself and we hope our paths will cross one day again, Hoang. 👏
